Set-Alias -Name "path" -Value "Get-PathEnvironmentVariable"
Set-Alias -Name "addpath" -Value "Update-PathEnvironmentVariable"
Set-Alias -Name "grep" -Value "rg"
Set-Alias -Name "vim" -Value "nvim"
Set-Alias -Name "vi" -Value "nvim"
Set-Alias -Name "hsd" -Value "horrible-downloader"
Set-Alias -Name "hsdl" -Value "horrible-downloader"
Set-Alias -name "winword" -Value "C:\Program Files\Microsoft Office 15\root\office15\winword.exe"
Set-Alias -Name "vlc" -Value "C:\Program Files\VideoLAN\VLC\vlc.exe"
Set-Alias -Name "audacity" -Value "C:\Program Files (x86)\Audacity\audacity.exe"

